import "bootstrap/dist/css/bootstrap.css";
// import "bootstrap/dist/js/bootstrap.min.js";
import "@/styles/globals.css";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="bootstrap/dist/js/bootstrap.js" />
      </Head>
      <nav className="navbar navbar-expand-lg navbar-light bg-light px-3">
        <h3 className="navbar-brand">Exam Sheets</h3>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div className="navbar-nav">
            <Link className="nav-item nav-link active" href="/">Home</Link>
          </div>
        </div>
      </nav>
      <main className={styles.main}>
        <div className="container">
          <Component {...pageProps} />
        </div>
      </main>
    </>
  );
  // return <Component {...pageProps} />
}
